## **Import Libraries**

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy.matlib
from sklearn import metrics 
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
%matplotlib inline

In [ ]:
df = pd.read_csv('Applais project.csv')
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,842,0,2.2,0,1,0,7,0.6,188.0,2,2,20,756,2549,9,7,19,0,0,1
1,1021,1,0.5,1,0,1,53,0.7,NaN,3,6,905,1988,2631,17,3,7,1,1,0
2,563,1,0.5,1,2,1,41,0.9,NaN,5,6,1263,1716,2603,11,2,9,1,1,0
3,615,1,2.5,0,0,0,10,0.8,NaN,6,9,1216,1786,2769,16,8,11,1,0,0
4,1821,1,1.2,0,13,1,44,0.6,NaN,2,14,1208,1212,1411,8,2,15,1,1,0

In [ ]:
df.shape

(2000, 20)

In [ ]:
print (df.isnull().sum())  
print (df.isnull().values.any())
print (df.isnull().values.sum())

battery_power      0
blue               0
clock_speed        0
dual_sim           0
fc                 0
four_g             0
int_memory         0
m_dep              0
mobile_wt        348
n_cores            0
pc                 0
px_height          0
px_width           0
ram                0
sc_h               0
sc_w               0
talk_time          0
three_g            0
touch_screen       0
wifi               0
dtype: int64
True
348

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
battery_power,2000.0,1238.518500,439.418206,501.0,851.75,1226.0,1615.25,1998.0
blue,2000.0,0.495000,0.500100,0.0,0.00,0.0,1.00,1.0
clock_speed,2000.0,1.522250,0.816004,0.5,0.70,1.5,2.20,3.0
dual_sim,2000.0,0.509500,0.500035,0.0,0.00,1.0,1.00,1.0
fc,2000.0,4.309500,4.341444,0.0,1.00,3.0,7.00,19.0
four_g,2000.0,0.521500,0.499662,0.0,0.00,1.0,1.00,1.0
int_memory,2000.0,32.046500,18.145715,2.0,16.00,32.0,48.00,64.0
m_dep,2000.0,0.501750,0.288416,0.1,0.20,0.5,0.80,1.0
mobile_wt,1652.0,140.325666,38.849169,80.0,104.00,151.0,177.00,200.0
n_cores,2000.0,4.520500,2.287837,1.0,3.00,4.0,7.00,8.0
pc,2000.0,9.916500,6.064315,0.0,5.00,10.0,15.00,20.0
px_height,2000.0,645.108000,443.780811,0.0,282.75,564.0,947.25,1960.0
px_width,2000.0,1251.515500,432.199447,500.0,874.75,1247.0,1633.00,1998.0
ram,2000.0,2124.213000,1084.732044,256.0,1207.50,2146.5,3064.50,3998.0
sc_h,2000.0,12.306500,4.213245,5.0,9.00,12.0,16.00,19.0
sc_w,2000.0,5.767000,4.356398,0.0,2.00,5.0,9.00,18.0
talk_time,2000.0,11.011000,5.463955,2.0,6.00,11.0,16.00,20.0
three_g,2000.0,0.761500,0.426273,0.0,1.00,1.0,1.00,1.0
touch_screen,2000.0,0.503000,0.500116,0.0,0.00,1.0,1.00,1.0
wifi,2000.0,0.507000,0.500076,0.0,0.00,1.0,1.00,1.0

In [ ]:
from numpy.core.fromnumeric import mean
M= df.fillna(df['mobile_wt'].mean())

In [ ]:
M.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,842,0,2.2,0,1,0,7,0.6,188.000000,2,2,20,756,2549,9,7,19,0,0,1
1,1021,1,0.5,1,0,1,53,0.7,140.325666,3,6,905,1988,2631,17,3,7,1,1,0
2,563,1,0.5,1,2,1,41,0.9,140.325666,5,6,1263,1716,2603,11,2,9,1,1,0
3,615,1,2.5,0,0,0,10,0.8,140.325666,6,9,1216,1786,2769,16,8,11,1,0,0
4,1821,1,1.2,0,13,1,44,0.6,140.325666,2,14,1208,1212,1411,8,2,15,1,1,0

In [ ]:
kmeans =KMeans(n_clusters = 3 , init = 'k-means++')
y_kmeans = kmeans.fit_predict(M)
centroids = kmeans.cluster_centers_
print(centroids)
iretation = 1000

[[1.22020906e+03 5.02923977e-01 1.52002924e+00 4.97076023e-01
  4.36695906e+00 5.21929825e-01 3.16622807e+01 5.00877193e-01
  1.39184736e+02 4.59210526e+00 1.01169591e+01 6.39334795e+02
  1.23363304e+03 2.20968860e+03 1.22923977e+01 5.83333333e+00
  1.12134503e+01 7.83625731e-01 4.95614035e-01 5.07309942e-01]
 [1.25073475e+03 4.73758865e-01 1.53546099e+00 4.89361702e-01
  4.18865248e+00 5.14893617e-01 3.15886525e+01 5.03971631e-01
  1.40804928e+02 4.46099291e+00 9.64822695e+00 6.58053901e+02
  1.25819574e+03 9.07625532e+02 1.23134752e+01 5.60567376e+00
  1.08709220e+01 7.41843972e-01 5.17730496e-01 4.90780142e-01]
 [1.24491980e+03 5.10638298e-01 1.50949264e+00 5.46644845e-01
  4.38461538e+00 5.28641571e-01 3.30049100e+01 5.00163666e-01
  1.41049914e+02 4.50900164e+00 1.00016367e+01 6.36633388e+02
  1.26382651e+03 3.43227987e+03 1.23142390e+01 5.87888707e+00
  1.09459902e+01 7.59410802e-01 4.94271686e-01 5.25368249e-01]]

In [ ]:
M["clusters"]=y_kmeans

In [ ]:
M.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,clusters
0,842,0,2.2,0,1,0,7,0.6,188.000000,2,...,20,756,2549,9,7,19,0,0,1,0
1,1021,1,0.5,1,0,1,53,0.7,140.325666,3,...,905,1988,2631,17,3,7,1,1,0,0
2,563,1,0.5,1,2,1,41,0.9,140.325666,5,...,1263,1716,2603,11,2,9,1,1,0,0
3,615,1,2.5,0,0,0,10,0.8,140.325666,6,...,1216,1786,2769,16,8,11,1,0,0,0
4,1821,1,1.2,0,13,1,44,0.6,140.325666,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [ ]:
X = M
y = M["clusters"].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 41)

In [ ]:
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.83      0.78      0.80        73
           1       0.97      0.91      0.94        67
           2       0.79      0.90      0.84        60

    accuracy                           0.86       200
   macro avg       0.86      0.86      0.86       200
weighted avg       0.86      0.86      0.86       200

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.86